# Generated by Django 5.2 on 2025-04-22 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_web', '0005_alter_contact_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='date',
            field=models.DateField(default='22:04:2025'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='time',
            field=models.TimeField(default='11:50:35'),
        ),
    ]
