# Generated by Django 5.1.7 on 2025-03-14 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='phone',
            field=models.IntegerField(default=0, max_length=14),
        ),
    ]
