# Generated by Django 5.1.7 on 2025-03-14 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_web', '0002_alter_contact_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='date',
            field=models.DateField(default='14:03:2025'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='time',
            field=models.TimeField(default='09:12:11'),
        ),
    ]
