# Generated by Django 5.1.7 on 2025-03-14 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_web', '0003_alter_contact_date_alter_contact_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='time',
            field=models.TimeField(default='09:19:50'),
        ),
    ]
