# Generated by Django 5.1.7 on 2025-03-14 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_web', '0004_alter_contact_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='time',
            field=models.TimeField(default='09:46:32'),
        ),
    ]
